spring:
  application:
    name: payment-service
  inetutils:
    prefer-ip-address: true
  datasource:
    url: jdbc:mysql://172.25.238.136:3307/payment_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 172.25.238.136:9092           # localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # http://eureka-server:8761/eureka/



